### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by knd775** [aymeric-giraudet/svelte-algolia-instantsearch#12]
The current release is missing a number of important changes that it'd be really nice to have. Please consider creating a new release. Thanks!

**Comment by dskelton-cos** [comment]
Yep it looks like a number of widgets are not included.  like  Highlight

**Comment by aymeric-giraudet** [comment]
Hey 👋 

I'll do that this weekend when I have time, along with some cleanup 😅

**Comment by aymeric-giraudet** [comment]
It's been released as `0.8.0` !
