### ISSUE TITLE
Svelte 4 TypeError

### ISSUE THREAD

**Issue by Finnepinnen** [aymeric-giraudet/svelte-algolia-instantsearch#14]
When updating this repo to svelte 4.2.0

The following error pops up in the console
`Uncaught (in promise) TypeError: fn is not a function`

Any ideas on the cause to this?

**Comment by djdembeck** [comment]
I see this issue as well - I think it's because the package targets svelte 3.

**Comment by aymeric-giraudet** [comment]
Hey, it's been fixed as of `0.9.1` !
