### ISSUE TITLE
Sveltekit 2 dependencies

### ISSUE THREAD

**Issue by mathg** [aymeric-giraudet/svelte-algolia-instantsearch#35]
Sveltekit 2 has been released this week but when upgrading I see this warning from Vite 

```
└─┬ svelte-algolia-instantsearch 0.12.0
  └── ✕ unmet peer @sveltejs/kit@">= 1 < 2": found 2
```
I ran my project with the upgraded version of sveltekit and the current of version of svelte-algolia-instantsearch and it's not breaking anything.

**Comment by aymeric-giraudet** [comment]
Done ! I'll look at the rest of the issues over the weekend
